
server:
  port: 8080
spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: aaa86925876
    url: jdbc:mysql://106.52.75.202:3306/pzforest?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai