logging:
  file:
    path: /var/wwwroot/
server:
  port: 8080
minio:
  url: http://106.52.75.202:9000
  accessKey: ZqGlbWR6ELbjxUPy
  secretKey: CmWxzWjkOiy23pAgHippO9Z5fw24q9dG
  api: s3v4
  path: auto
  bucketName: pzforest
pzforest:
  access-token:
    - "2.00Cr7AhCFlne1D50224d9dadjIQdBE"
    - "2.00Cr7AhCxWGpzC70aeafc18fUlNDnB"
    - "2.00Cr7AhCbIFBmC2d5ff123e3QHloED"
    - "2.00Cr7AhC48cw9D47acd367abcSMdDC"
    - "2.00Cr7AhC9pAvNE3f037476cagSG15E"
spring:
  data:
    redis:
      host: 106.52.75.202
      port: 6379
      database: 0
      password: 95270625
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: aaa86925876
    url: jdbc:mariadb://106.52.75.202:3306/pzforest?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size:
        100MB
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: pzforest
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
